### ISSUE TITLE
No documetation?

### ISSUE THREAD

**Issue by SaphiLC** [front/g-editor#16]
mmm, how do we use this? i see no docs :S

**Comment by SofiaSousa** [comment]
It's described in the [readme](https://github.com/front/g-editor/blob/master/README.md) file.

**Comment by SaphiLC** [comment]
Use as in use, not as in installing, so no, it is not described in the readme file. If you expect ppl to magically know all the functions you can use in this package... but is ok, already using something better documented.

**Comment by SofiaSousa** [comment]
Probably g-editor was not what you needed/expected. 

I'm glad you found the tool you needed.
