### ISSUE TITLE
Embed not working

### ISSUE THREAD

**Issue by Arlien** [front/g-editor#18]
Hello, the embed blocks (twitter, spotify, instagram,...) are not working at all. There's a problem with the routes. Here's the error : ﻿
<pre>Unmatched route: GET /oembed/1.0/proxy?url=https%3A%2F%2Finstagram.com%2Fprivarlien&_locale=user undefined
console.<computed> @ index.js:1437
apiFetch @ api-fetch.js:83
(anonymous) @ index.js:1
(anonymous) @ index.js:1
tryCatch @ wp-polyfill.min.js:3
invoke @ wp-polyfill.min.js:3
t.<computed> @ wp-polyfill.min.js:3
r @ index.js:1
c @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
m @ index.js:1
(anonymous) @ index.js:1
c @ index.js:1
(anonymous) @ index.js:1
m @ index.js:1
(anonymous) @ index.js:1
t @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
c @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
k @ index.js:1
API_FETCH @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
n @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
t @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
tryCatch @ wp-polyfill.min.js:3
invoke @ wp-polyfill.min.js:3
t.<computed> @ wp-polyfill.min.js:3
n @ index.js:1
c @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
J @ index.js:1
(anonymous) @ index.js:1
tryCatch @ wp-polyfill.min.js:3
invoke @ wp-polyfill.min.js:3
t.<computed> @ wp-polyfill.min.js:3
n @ index.js:1
c @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
a @ index.js:1
(anonymous) @ index.js:1
u @ index.js:1
(anonymous) @ index.js:14
(anonymous) @ index.js:1
jt @ index.js:1
(anonymous) @ index.js:1
Td @ react-dom.production.min.js:82
be @ react-dom.production.min.js:91
hi @ react-dom.production.min.js:104
Qg @ react-dom.production.min.js:144
Rg @ react-dom.production.min.js:145
Sc @ react-dom.production.min.js:158
Z @ react-dom.production.min.js:156
ah @ react-dom.production.min.js:159
xf @ react-dom.production.min.js:40
</pre>
Anybody encountering the same problem ? I don't know how to solve it and it's blocking me, help :)

**Comment by SofiaSousa** [comment]
Hi @Arlien,

Embed block is now working in the editor:
**v1.5.0** :tada: 

We added the route that was missing (`GET /oembed/1.0/proxy`) and included [oember-providers](https://www.npmjs.com/package/oembed-providers) to get the providers urls.

To fetch embed cards, we are using the [cors-anywhere](https://cors-anywhere.herokuapp.com/) proxy, which enables the cross-origin requests to providers.

I hope it helps you and your work :slightly_smiling_face:

Happy Easter 
:rabbit:
