### ISSUE TITLE
Editor state from "Submit for Review" to direct "Save"

### ISSUE THREAD

**Issue by Qoraiche** [front/g-editor#2]
The default state for the editor is set by default to publish "Submit for Review". How i can change the editor state to direct "Save" or "Schedule".

I hope someone answer my question.
Thanks

**Comment by SofiaSousa** [comment]
Hi @Qoraiche,

It depends on the post status. The g-editor sets the post as a [draft](https://github.com/front/g-editor/blob/master/src/globals/fake-data.js#L43) by default. 

Changing the status will make that differents options be displayed in the editor. Here is the list of [default statuses](https://codex.wordpress.org/Post_Status#Default_Statuses).

Does it help you?

**Comment by Qoraiche** [comment]
Thanks, @SofiaSousa! yes that helps me a lot, please i have one more question here:

https://github.com/front/gutenberg-js/issues/22#issue-403978157

**Comment by Qoraiche** [comment]
@SofiaSousa Unfortunately I change the default status but still the same!

**Comment by SofiaSousa** [comment]
We've noticed the status is not being updated when the page is saved. 

Besides that, some of the behavior you expected occurs only for posts. For now, the g-editor only supports [page](https://github.com/front/g-editor/blob/develop/src/globals/fake-data.js#L5) post type.

**Comment by Qoraiche** [comment]
@SofiaSousa is there any other way to change the editor status? something like dispatching manually, because this seems to be useless without changing the behavior of the editor. please help with this thanks.

**Comment by SofiaSousa** [comment]
Hi @Qoraiche,

The `post` post type has been added to v0.4.0-rc.1. Now we can switch between `page`or `post` post types in the editor. 

Can you test it before the final release?

**Comment by Qoraiche** [comment]
Hi, yes it's working thanks, but the status still not being updated! for example, I don't want the button "Move to trash" to be visible until the post published, As well the "publish" (not "Submit for review") button must be changed to "Update" when the post published. I try to change the post/page status but not working.

I'm working to achieve it on my local server, I will share the solution if I figured it out.
thanks.

**Comment by SofiaSousa** [comment]
I think we probably are not mimicking the whole save/change status process from the WordPress. Some attributes could be not being updated as WP does and the Gutenberg editor expects.

**Comment by Qoraiche** [comment]
@SofiaSousa ah okay, thanks btw
