### ISSUE TITLE
dynamic blocks

### ISSUE THREAD

**Issue by amirrahimi71** [front/g-editor#22]
Hi @SofiaSousa 
does g-editor support dynamic-blocks? If yes, is there any guidance on this?

**Comment by SofiaSousa** [comment]
Hi @amirrahimi71,

For most of the dynamic blocks, the `save` callback function is implemented and rendered at server side (in WordPress with PHP for example). So the g-editor will only handle with the edit part of the block in the editor.

Source: https://developer.wordpress.org/block-editor/tutorials/block-tutorial/creating-dynamic-blocks/

Would you like to describe the problem/requirements your are facing?

**Comment by amirrahimi71** [comment]
Thanks for the reply
In fact, I want to create a dynamic block and do the server side rendering in asp.net. 
Is there a way to do that?

**Comment by SofiaSousa** [comment]
Gutenberg saves a reference of the block and its settings as comments. For exemple for **Latest Post** dynamic block:

`<!-- wp:latest-posts {"displayPostContent":true,"displayAuthor":true,"displayPostDate":true} /-->`

So you might be able to handle dynamic blocks when rendering on server side by parsing those comments.
