### ISSUE TITLE
how to prevent to add "/?post=1&action=edit" to url

### ISSUE THREAD

**Issue by amirrahimi71** [front/g-editor#24]
hi @SofiaSousa 
how to prevent to add /?post=1&action=edit to url when add data to local storage like https://demo.gutenbergcloud.org/

**Comment by SofiaSousa** [comment]
Hi @amirrahimi71 

We used to override **add_query_args** (from @wordpress/url package) https://github.com/WordPress/gutenberg/blob/master/packages/url/src/add-query-args.js, which is the method responsible for appending arguments as querystring to URLs. But that's something we don't do anymore.
