### ISSUE TITLE
Add a video or two to "fake" media library

### ISSUE THREAD

**Issue by vonloxx** [front/g-editor#3]
It would be very handy to test videos without uploading on some situations ;)
Some suggestions to keep the cat theme 😸
https://pixabay.com/en/videos/cute-cat-funny-cat-kitten-domestic-3092/
https://pixabay.com/en/videos/cat-cat-thailand-small-indian-civet-1297/

**Comment by SofiaSousa** [comment]
Loved your suggestions :heart_eyes_cat: 

2 videos have been added to [v0.4.0-rc.1](https://github.com/front/g-editor/tree/v0.4.0-rc.1) and the preview mode of video has also fixed. Can you test it before the final release?
