### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by Qoraiche** [front/g-editor#4]
Hi,

Why I get this error in the browser console when I build and serve the index file:
`TypeError: Super expression must either be null or a function, not undefined`

Is there any solution?

@SofiaSousa your help needed

**Comment by arnvanhoutte** [comment]
It is because you are building with optimizations on

**Comment by Qoraiche** [comment]
@arnvanhoutte thanks for the reply, so what is the solution?

**Comment by arnvanhoutte** [comment]
At the moment: turning optimizations off.

It is related to https://github.com/front/gutenberg-js/issues/18 and https://github.com/front/gutenberg-js/issues/14

**Comment by Qoraiche** [comment]
@arnvanhoutte but this only related to your repository that uses angular, how I can turn off optimizations on gutenberg-js

**Comment by SofiaSousa** [comment]
This is not a **g-editor** issue.

Closing
